version: "3.7"

services:

  ########################################################
  ### LOADERS
  ########################################################

  af-loader-basic:
    container_name: af-loader-basic
    hostname: af-loader-basic
    restart: on-failure
    image: fernandodumont/acme-flights-loaders:3.0
    environment:
      - ENABLE_BASE_LOAD=1
    env_file: ./appdynamics/controller.env
    volumes:
      - ./loaders/base-load.yml:/app/base-load/base-load.yml

  af-loader-use-case:
    container_name: af-loader-use-case
    hostname: af-loader-use-case
    restart: on-failure
    image: fernandodumont/acme-flights-loaders:3.0
    environment:
      - ENABLE_USE_CASES_LOAD=1
    env_file: ./appdynamics/controller.env
    volumes:
      - ./loaders/use-cases.yml:/app/use-cases/use-cases.yml

  ########################################################
  ### NGINX
  ########################################################

  af-web:
    image: fernandodumont/acme-flights-web:3.0
    container_name: af-web
    hostname: af-web
    restart: on-failure
    expose:
      - 8154
    ports:
      - 8154:8154
    volumes:
      - ./web/appd.js:/usr/share/nginx/html/assets/appd.js
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/use-cases.json:/usr/share/nginx/html/assets/use-cases.json

  ########################################################
  ### JAVA SERVICES
  ########################################################

  af-api-manager:
    container_name: af-api-manager
    hostname: af-api-manager
    restart: on-failure
    image: fernandodumont/acme-flights-java-services:3.0
    expose:
      - 8001
    ports:
      - 8001:8080
    env_file: ./appdynamics/controller.env
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=api-manager
      - APPDYNAMICS_AGENT_NODE_NAME=api-manager-1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - java-agent-acme:/opt/appdynamics/java-agent/

  af-internal-services:
    container_name: af-internal-services
    hostname: af-internal-services
    restart: on-failure
    image: fernandodumont/acme-flights-java-services:3.0
    env_file: ./appdynamics/controller.env
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=internal-services
      - APPDYNAMICS_AGENT_NODE_NAME=internal-services-1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - java-agent-acme:/opt/appdynamics/java-agent/

  af-external-services:
    container_name: af-external-services
    hostname: af-external-services
    restart: on-failure
    image: fernandodumont/acme-flights-java-services:3.0
    env_file: ./appdynamics/controller.env
    environment:
      - AUDIT=true
      - JAVA_TOOL_OPTIONS=-javaagent:/opt/appdynamics/java-agent/javaagent.jar
      - APPDYNAMICS_AGENT_TIER_NAME=external-services
      - APPDYNAMICS_AGENT_NODE_NAME=external-services-1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - java-agent-acme:/opt/appdynamics/java-agent/

  ########################################################
  ### BACKENDS
  ########################################################

  af-mongo:
    image: fernandodumont/acme-flights-mongo:3.0
    container_name: af-mongo
    hostname: af-mongo
    restart: on-failure
    expose:
      - 27017
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    hostname: mongo-express
    restart: on-failure
    expose:
      - 8081
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://af-mongo:27017

  af-mysql:
    image: fernandodumont/acme-flights-mysql:3.0
    container_name: af-mysql
    hostname: af-mysql
    restart: on-failure
    expose:
      - 3306
    ports:
      - 3306:3306

  af-ldap:
    image: bitnami/openldap:latest
    container_name: af-ldap
    hostname: af-ldap
    restart: on-failure
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin1
      - LDAP_USERS=acmeflight
      - LDAP_PASSWORDS=acmeflight1
    expose:
      - 1389
      - 1636
    ports:
      - 1389:1389
      - 1636:1636

  ########################################################
  ### Mock Services
  ########################################################
  
  sap-services:
    container_name: sap-services
    hostname: sap-services
    restart: on-failure
    image: fernandodumont/acme-flights-java-services:3.0

  finance-services:
    container_name: finance-services
    hostname: finance-services
    restart: on-failure
    image: fernandodumont/acme-flights-java-services:3.0

  ########################################################
  ### AppDynamics
  ########################################################

  java-agent-acme:
    container_name: java-agent-acme
    hostname: java-agent-acme
    image: appdynamics/java-agent:latest
    volumes:
      - java-agent-acme:/opt/appdynamics

  af-machine-agent:
    build:
      context: ./
      dockerfile: ./machine-agent/Dockerfile
    container_name: af-machine-agent
    image: appdynamics/machine-agent-netviz:22.9.0.3458
    env_file: ./appdynamics/controller.env
    network_mode: "host"
    environment:
      - APPDYNAMICS_SIM_ENABLED=true
      - APPDYNAMICS_DOCKER_ENABLED=true
      - APPDYNAMICS_AGENT_ENABLE_CONTAINERIDASHOSTID=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/hostroot:ro
    cap_add:
      - NET_ADMIN
      - NET_RAW
    expose:
      - 3892
      - 9090

  af-database-agent:
    container_name: af-database-agent
    hostname: af-database-agent
    image: appdynamics/db-agent:latest
    env_file: ./appdynamics/controller.env
    environment:
      - APPDYNAMICS_DB_AGENT_NAME=ACME-Databases
    
volumes:
  java-agent-acme:

networks:
  acme-flights-net:
    ipam:
        driver: default
        config:
            - subnet: 1.1.1.1/16
              gateway: 1.1.1.1