version: "3.7"

services:

  ########################################################
  ### NGINX
  ########################################################

  af-web:
    image: fernandodumont/acme-flights-web:3.0
    container_name: af-web
    hostname: af-web
    restart: on-failure
    expose:
      - 8154
    ports:
      - 8154:8154
    volumes:
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      - ./web/use-cases.json:/usr/share/nginx/html/assets/use-cases.json
    networks:
      - acme-flights-net

  ########################################################
  ### JAVA SERVICES
  ########################################################

  af-api-manager:
    container_name: af-api-manager
    hostname: af-api-manager
    restart: on-failure
    image: fernandodumont/acme-flights-java-services:3.0
    expose:
      - 8001
    ports:
      - 8001:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - acme-flights-net

  af-internal-services:
    container_name: af-internal-services
    hostname: af-internal-services
    restart: on-failure
    image: fernandodumont/acme-flights-java-services:3.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - acme-flights-net
    
  af-external-services:
    container_name: af-external-services
    hostname: af-external-services
    restart: on-failure
    image: fernandodumont/acme-flights-java-services:3.0
    environment:
      - AUDIT=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - acme-flights-net

  ########################################################
  ### BACKENDS
  ########################################################

  af-mongo:
    image: fernandodumont/acme-flights-mongo:3.0
    container_name: af-mongo
    hostname: af-mongo
    restart: on-failure
    expose:
      - 27017
    ports:
      - 27017:27017
    networks:
      - acme-flights-net

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    hostname: mongo-express
    restart: on-failure
    expose:
      - 8081
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://af-mongo:27017
    networks:
      - acme-flights-net

  af-mysql:
    image: fernandodumont/acme-flights-mysql:3.0
    container_name: af-mysql
    hostname: af-mysql
    restart: on-failure
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      - acme-flights-net

  af-ldap:
    image: bitnami/openldap:latest
    container_name: af-ldap
    hostname: af-ldap
    restart: on-failure
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=admin1
      - LDAP_USERS=acmeflight
      - LDAP_PASSWORDS=acmeflight1
    expose:
      - 1389
      - 1636
    ports:
      - 1389:1389
      - 1636:1636
    networks:
      - acme-flights-net
      
  # ########################################################
  # ### Mock Services
  # ########################################################
  
  sap-services:
    container_name: sap-services
    hostname: sap-services
    restart: on-failure
    image: fernandodumont/acme-flights-java-services:3.0
    networks:
      - acme-flights-net
      
  finance-services:
    container_name: finance-services
    hostname: finance-services
    restart: on-failure
    image: fernandodumont/acme-flights-java-services:3.0
    networks:
      - acme-flights-net

networks:
  acme-flights-net:
    ipam:
        driver: default
        config:
            - subnet: 1.1.1.1/16
              gateway: 1.1.1.1